#!/usr/bin/env sh

## -- Terminal
super + Return
	alacritty
## -- Launcher Menu
super + @space
  $HOME/.config/rofi/bin/launcher
## -- Run
super + shift + r
  $HOME/.config/rofi/bin/runner
## -- Screenshot
super + shift + p
  $HOME/.config/rofi/bin/screenshot

## -- Restart sxhkd
super + alt + Escape
	pkill -USR1 -x sxhkd && dunstify "sxhkd" "Restart"

# quit/restart bspwm
super + alt + {q,r}
	bspc {quit,wm -r && dunstify "bspwm" "Restart"}

# close and kill
super + {_,shift + }w
	bspc node -{c,k}

# alternate between the tiled and monocle layout
super + m
	bspc desktop -l next


# state/flags
# set the window state
super + {t,shift + t,s,f}
	bspc node -t {tiled,pseudo_tiled,floating,fullscreen}

# focus/swap
# focus the node in the given direction
super + {_,shift + }{Left,Down,Up,Right}
	bspc node -{f,s} {west,south,north,east}

# focus the last node/desktop
super + {grave,Tab}
	bspc {node,desktop} -f last

# focus or send to the given desktop
super + {_,shift + }{1-9,0}
	bspc {desktop -f,node -d} '^{1-9,10}'

# preselect
# preselect the direction
super + ctrl + {Left,Down,Up,Right}
	bspc node -p {west,south,north,east}

# cancel the preselection for the focused node
super + ctrl + space
	bspc node -p cancel

# preselect the ratio
super + ctrl + {1-9}
	bspc node -o 0.{1-9}

# move/resize
# expand a window by moving one of its side outward
super + alt + {Left,Down,Up,Right}
	bspc node -z {left -20 0,bottom 0 20,top 0 -20,right 20 0}

# contract a window by moving one of its side inward
super + alt + shift + {Left,Down,Up,Right}
	bspc node -z {right -20 0,top 0 20,bottom 0 -20,left 20 0}

# move a floating window
super + {Left,Down,Up,Right}
	bspc node -v {-20 0,0 20,0 -20,20 0}
