#!/bin/zsh

unalias run-help
unalias which-command

alias reload="echo 'Reloading ${SHELL}...'; exec '$SHELL' -l"
alias path='echo -e ${PATH//:/\\n}'
alias dot='/usr/bin/git --git-dir=$HOME/.dotfiles --work-tree=$HOME'

# COMMON
alias cat="$(which bat)"
alias cp='cp -iv'
alias mv='mv -iv'
alias mkd='mkdir -p'

# LS
alias ls="$(which exa)"
alias la="ls -la --group-directories-first --git"

# GREP
alias grep="grep --color=auto"
alias egrep="egrep --color=auto"
alias fgrep="fgrep --color=auto"
alias rgrep="rgrep --color=auto"
alias diff="diff --color=auto"

# XCLIP
alias setclip="xclip -sel clipboard -i"
alias getclip="xclip -sel clipboard -o"

# YTDL
alias ytdl="yt-dlp"
alias ytmp3="yt-dlp -x --audio-format mp3 --audio-quality 0"

if [ "$TERM" = "alacritty" ]; then
  alias ssh="TERM=xterm-256color ssh"
fi
