#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8

bspc config border_width		1
bspc config top_padding			30
bspc config left_padding		17
bspc config right_padding		17
bspc config bottom_padding		10

bspc config focused_border_color	"#56949f"
bspc config normal_border_color		"#6e6a86"

bspc config split_ratio			0.52
bspc config borderless_monocle		true
bspc config single_monocle		true
bspc config gapless_monocle		false
bspc config focus_follows_pointer	true
bspc config remove_disabled_monitors	true
bspc config remove_unplugged_monitors	true

bspc rule -a alacritty desktop='^1' follow='on'
bspc rule -a discord desktop='^2' follow='on'
bspc rule -a telegram-desktop desktop='^2' follow='on'
bspc rule -a firefox desktop='^3' follow='on'

picom -b &

xrdb -merge $HOME/.Xresources &

hsetroot -cover $HOME/Pictures/Wallpapers/Img03.jpg &
xsetroot -cursor_name left_ptr &

$HOME/.config/polybar/launch.sh &

