#! /bin/sh
killall -g sxhkd polybar mpd picom
pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6

bspc config border_width 1
bspc config window_gap 12

bspc config focused_border_color "#56949f"
bspc config normal_border_color "#6e6a86"

bspc config split_ratio 0.50
bspc config borderless_monocle true
bspc config single_monocle true
bspc config gapless_monocle false
bspc config focus_follows_pointer	true
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors	true

bspc rule -a firefox desktop='^2' follow='on'
bspc rule -a discord desktop='^3' follow='on'

bspc rule -a Lxappearance state='floating'
bspc rule -a Pavucontrol state='floating'
bspc rule -a qt5ct state='floating'
bspc rule -a TelegramDesktop state='floating'

hsetroot -cover $HOME/Pictures/Img01.png &
mpd &
picom &
$HOME/.config/polybar/launch.sh &
xsetroot -cursor_name left_ptr &
xset s 0 0
xset dpms 0 0 0
