#! /bin/sh
pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6

bspc config border_width              1
bspc config window_gap                10

bspc config focused_border_color      "#56949f"
bspc config normal_border_color       "#6e6a86"

bspc config split_ratio                 0.50
bspc config borderless_monocle          true
bspc config single_monocle              true
bspc config gapless_monocle             false
bspc config focus_follows_pointer	      false
bspc config remove_disabled_monitors    true
bspc config remove_unplugged_monitors	  true
bspc config pointer_modifier            mod4

bspc rule -r '*'
bspc rule -a Alacritty desktop='^1' follow='on'
bspc rule -a discord desktop='^2' follow='on'
bspc rule -a TelegramDesktop desktop='^2' follow='on'
bspc rule -a LibreWolf desktop='^3' follow='on'
bspc rule -a pyrogenesis desktop='^6' state='fullscreen' follow='on'

bspc rule -a dolphin-emu state='floating'
bspc rule -a Lxappearance state='floating'
bspc rule -a Pavucontrol state='floating'
bspc rule -a Qt5ct state='floating'
bspc rule -a Nm-connection-editor state='floating'

$HOME/.config/autostart/launch &
